// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encrypted_info.proto

package encryption

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EncryptedInfo struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Sign                 []byte   `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedInfo) Reset()         { *m = EncryptedInfo{} }
func (m *EncryptedInfo) String() string { return proto.CompactTextString(m) }
func (*EncryptedInfo) ProtoMessage()    {}
func (*EncryptedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3d049612eb23e7b, []int{0}
}

func (m *EncryptedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedInfo.Unmarshal(m, b)
}
func (m *EncryptedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedInfo.Marshal(b, m, deterministic)
}
func (m *EncryptedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedInfo.Merge(m, src)
}
func (m *EncryptedInfo) XXX_Size() int {
	return xxx_messageInfo_EncryptedInfo.Size(m)
}
func (m *EncryptedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedInfo proto.InternalMessageInfo

func (m *EncryptedInfo) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EncryptedInfo) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*EncryptedInfo)(nil), "models.EncryptedInfo")
}

func init() { proto.RegisterFile("encrypted_info.proto", fileDescriptor_c3d049612eb23e7b) }

var fileDescriptor_c3d049612eb23e7b = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x49, 0x4d, 0x89, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56, 0xb2, 0xe5, 0xe2, 0x75, 0x85, 0xc9, 0x7b,
	0xe6, 0xa5, 0xe5, 0x0b, 0x49, 0x70, 0xb1, 0x97, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x49, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xb8, 0x42, 0x42, 0x5c, 0x2c, 0xc5, 0x99, 0xe9, 0x79, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0x76, 0x12, 0x1b, 0xd8, 0x34, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x77, 0xf1, 0xc0, 0x96, 0x65, 0x00, 0x00, 0x00,
}
